FROM demo_appserverbase

MAINTAINER Thomas Qvarnstrom <tqvarnst@redhat.com>

# Set the Java Opts
ENV EAP_VERSION 6.4.0

ADD ticket-monster.war /opt/jboss/jboss-eap-${EAP_VERSION}/standalone/deployments/ 


